version: "3.7"

services:
  aj-backend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: aj-backend
    tty: true
    entrypoint: sh ./.docker/entrypoint.sh
    environment:
      PORT: 3030
      MONGO_DB_URI: "mongodb+srv://${AJ_MONGO_USER}:${AJ_MONGO_PASS}@armarinho-cluster-1.65mpi.mongodb.net/core?retryWrites=true&w=majority"
    ports:
      - 3030:3030
    volumes:
      - ./:/usr/aj-backend/app
    networks:
      - aj-backend

networks:
  aj-backend:
    driver: bridge
