version: "3.7"

services:
  aj-backend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: aj-backend
    tty: true
    entrypoint: sh ./.docker/entrypoint.sh
    environment:
      PORT: 3030
    ports:
      - 3030:3030
    volumes:
      - ./:/usr/aj-backend/app
    networks:
      - aj-backend

networks:
  aj-backend:
    driver: bridge
